apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
        - name: MYSQL_USER
          value: root
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
        - name: MYSQLDB_DATABASE
          value: app_users_db
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql57-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql57-persistent-storage
        persistentVolumeClaim:
          claimName: mysql57-pv-claim
