apiVersion: v1
kind: Service
metadata:
  name: node
spec:
  type: LoadBalancer
  selector:
    app: node
  ports:
    - port: 8181 # expose the service on internal port 8181
      targetPort: 9090 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
spec:
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node
        image: hanafi05/bbph_pengguna
        ports:
        - containerPort: 9090
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
