module.exports = {
  ACCESS_TOKEN_SECRET: "qwerty123321ytrewq2021",
  REFRESH_TOKEN_SECRET: "SIGIT-NURHANAFI-2021",
  ACCESS_TOKEN_EXPIRATION: "1d",
  REFRESH_TOKEN_EXPIRATION: "7d",
  ROLE_ADMIN : 1,
  ROLE_USER : 2,
};
